name: clordle
description: A Wordle clone built for the command line with Dart. Have fun!
version: 0.0.1-dev.2
repository: https://github.com/Luckey-Elijah/clordle

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0

dependencies:
  args: ^2.3.0
  equatable: ^2.0.3
  mason_logger: ^0.1.0-dev.6

executables:
  clordle: